# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main-window.ui'
#
# Created: Thu May 15 00:43:50 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(380, 651)
        mainWindow.setMinimumSize(QtCore.QSize(380, 0))
        mainWindow.setMaximumSize(QtCore.QSize(380, 668))
        mainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/triangular7.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget = QtGui.QWidget(mainWindow)
        self.widget.setGeometry(QtCore.QRect(9, 9, 345, 637))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(20, 10, -1, -1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.labelCamera = QtGui.QLabel(self.widget)
        self.labelCamera.setMinimumSize(QtCore.QSize(320, 240))
        self.labelCamera.setMaximumSize(QtCore.QSize(320, 240))
        self.labelCamera.setText(_fromUtf8(""))
        self.labelCamera.setObjectName(_fromUtf8("labelCamera"))
        self.verticalLayout.addWidget(self.labelCamera)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.buttonTakePicture = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonTakePicture.sizePolicy().hasHeightForWidth())
        self.buttonTakePicture.setSizePolicy(sizePolicy)
        self.buttonTakePicture.setMinimumSize(QtCore.QSize(120, 40))
        self.buttonTakePicture.setMaximumSize(QtCore.QSize(120, 40))
        self.buttonTakePicture.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonTakePicture.setObjectName(_fromUtf8("buttonTakePicture"))
        self.horizontalLayout.addWidget(self.buttonTakePicture)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 10, -1, 30)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.buttonCircle = QtGui.QPushButton(self.widget)
        self.buttonCircle.setMinimumSize(QtCore.QSize(100, 80))
        self.buttonCircle.setMaximumSize(QtCore.QSize(100, 80))
        self.buttonCircle.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/circle46.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonCircle.setIcon(icon1)
        self.buttonCircle.setIconSize(QtCore.QSize(80, 60))
        self.buttonCircle.setObjectName(_fromUtf8("buttonCircle"))
        self.horizontalLayout_2.addWidget(self.buttonCircle)
        self.buttonTriangle = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonTriangle.sizePolicy().hasHeightForWidth())
        self.buttonTriangle.setSizePolicy(sizePolicy)
        self.buttonTriangle.setMinimumSize(QtCore.QSize(100, 80))
        self.buttonTriangle.setMaximumSize(QtCore.QSize(100, 80))
        self.buttonTriangle.setText(_fromUtf8(""))
        self.buttonTriangle.setIcon(icon)
        self.buttonTriangle.setIconSize(QtCore.QSize(60, 60))
        self.buttonTriangle.setObjectName(_fromUtf8("buttonTriangle"))
        self.horizontalLayout_2.addWidget(self.buttonTriangle)
        self.buttonRectangle = QtGui.QPushButton(self.widget)
        self.buttonRectangle.setMinimumSize(QtCore.QSize(100, 80))
        self.buttonRectangle.setMaximumSize(QtCore.QSize(100, 80))
        self.buttonRectangle.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/rectangular43.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRectangle.setIcon(icon2)
        self.buttonRectangle.setIconSize(QtCore.QSize(100, 80))
        self.buttonRectangle.setObjectName(_fromUtf8("buttonRectangle"))
        self.horizontalLayout_2.addWidget(self.buttonRectangle)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.buttonExit1 = QtGui.QPushButton(self.widget)
        self.buttonExit1.setObjectName(_fromUtf8("buttonExit1"))
        self.verticalLayout_2.addWidget(self.buttonExit1)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame = QtGui.QFrame(self.widget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label1 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.label1.setFont(font)
        self.label1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.horizontalLayout_4.addWidget(self.label1)
        self.line1 = QtGui.QLineEdit(self.frame)
        self.line1.setMinimumSize(QtCore.QSize(70, 30))
        self.line1.setMaximumSize(QtCore.QSize(70, 30))
        self.line1.setObjectName(_fromUtf8("line1"))
        self.horizontalLayout_4.addWidget(self.line1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label2 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2.sizePolicy().hasHeightForWidth())
        self.label2.setSizePolicy(sizePolicy)
        self.label2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label2.setObjectName(_fromUtf8("label2"))
        self.horizontalLayout_3.addWidget(self.label2)
        self.line2 = QtGui.QLineEdit(self.frame)
        self.line2.setMinimumSize(QtCore.QSize(70, 30))
        self.line2.setMaximumSize(QtCore.QSize(70, 30))
        self.line2.setObjectName(_fromUtf8("line2"))
        self.horizontalLayout_3.addWidget(self.line2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label3 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3.sizePolicy().hasHeightForWidth())
        self.label3.setSizePolicy(sizePolicy)
        self.label3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label3.setObjectName(_fromUtf8("label3"))
        self.horizontalLayout_5.addWidget(self.label3)
        self.line3 = QtGui.QLineEdit(self.frame)
        self.line3.setMinimumSize(QtCore.QSize(70, 30))
        self.line3.setMaximumSize(QtCore.QSize(70, 30))
        self.line3.setObjectName(_fromUtf8("line3"))
        self.horizontalLayout_5.addWidget(self.line3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        spacerItem = QtGui.QSpacerItem(72, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.buttonWriteToPlotter = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonWriteToPlotter.sizePolicy().hasHeightForWidth())
        self.buttonWriteToPlotter.setSizePolicy(sizePolicy)
        self.buttonWriteToPlotter.setObjectName(_fromUtf8("buttonWriteToPlotter"))
        self.horizontalLayout_6.addWidget(self.buttonWriteToPlotter)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.buttonBack = QtGui.QPushButton(self.widget)
        self.buttonBack.setObjectName(_fromUtf8("buttonBack"))
        self.gridLayout_2.addWidget(self.buttonBack, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 0, 1, 1)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "Two Axis Plotter Client", None))
        self.buttonTakePicture.setText(_translate("mainWindow", "Take a Picture", None))
        self.buttonExit1.setText(_translate("mainWindow", "Exit", None))
        self.label1.setText(_translate("mainWindow", "a", None))
        self.label2.setText(_translate("mainWindow", "b", None))
        self.label3.setText(_translate("mainWindow", "c", None))
        self.buttonWriteToPlotter.setText(_translate("mainWindow", "Write to Plotter", None))
        self.buttonBack.setText(_translate("mainWindow", "Back", None))

import resource_rc
